import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'hi': {
          "choose language": "भाषा चुनें",
          "profile": "प्रोफ़ाइल",
          "edit profile": "प्रोफ़ाइल संपादित करें",
          "change password": "पासवर्ड बदलें",
          "bookmarks": "बुकमार्क",
          "language": "भाषा",
          "app settings": "एप्लिकेशन सेटिंग",
          "logout": "लॉग आउट",
          "change profile photo": "प्रोफ़ाइल फ़ोटो बदलें",
          "username": "उपयोगकर्ता नाम",
          "email": "ईमेल",
          "contact no": "संपर्क नंबर।",
          "save changes": "परिवर्तनों को सुरक्षित करें",
          "current password": "वर्तमान पासवर्ड",
          "type current password here": "यहां करंट पासवर्ड टाइप करें",
          "new password": "नया पासवर्ड",
          "type new password here": "यहां नया पासवर्ड टाइप करें",
          "confirm new password": "नए पासवर्ड की पुष्टि करें",
          "type confirm new password here": "यहां कन्फर्म न्यू पासवर्ड टाइप करें",
          "update password": "पासवर्ड अपडेट करें",
          "details": "विवरण",
          "call": "पुकारना",
          "chat": "बात करना",
          "month": "महीना",
          "govt. charges": "सरकार. प्रभार",
          "description": "विवरण",
          "published on": "पर प्रकाशित",
          "sales enquiries": "बिक्री पूछताछ",
          "app settings screen": "ऐप सेटिंग्स स्क्रीन",
          "display": "प्रदर्शन",
          "dark mode": "डार्क मोड",
          "display mode": "प्रदर्शन प्रणाली",
          "choose how your flutter ui kit experience looks for this device...": "चुनें कि इस डिवाइस के लिए आपका फ़्लटर यूआई किट अनुभव कैसा दिखेगा...",
          "device settings": "उपकरण सेटिंग्स",
          "light mode": "लाइट मोड",
          "if you choose device settings, this app will use the mode that's already selected in this device's settings.": "यदि आप डिवाइस सेटिंग चुनते हैं, तो यह ऐप उस मोड का उपयोग करेगा जो इस डिवाइस की सेटिंग में पहले से ही चयनित है।",
          "what are looking for?": "आपको क्या चाहिए?",
          "current location": "वर्तमान स्थान",
          "house": "घर",
          "flats / apartments": "फ्लैट/अपार्टमेंट",
          "residential": "आवासीय",
          "commercial": "व्यावसायिक",
          "2000+ results": "2000+ परिणाम",
          "5000+ results": "5000+ परिणाम",
          "1000+ results": "1000+ परिणाम",
          "recommend for you": "आपके लिए अनुशंसा",
          "home": "घर",
          "location": "जगह",
          "search location": "स्थान खोजें",
          "chats": "चैट",
          "search by name": "नाम से खोजें",
          "search by street/area/city": "सड़क/क्षेत्र/शहर के आधार पर खोजें",
          "use my current location": "मेरे वर्तमान स्थान का उपयोग करें",
          "recent searches": "हाल की खोजें",
          "view more": "और देखें",
          "type message here": "यहां संदेश टाइप करें",
        },
        'gu': {
          "choose language": "ભાષા પસંદ કરો",
          "profile": "પ્રોફાઇલ",
          "edit profile": "પ્રોફાઇલ સંપાદિત કરો",
          "change password": "પાસવર્ડ બદલો",
          "bookmarks": "બુકમાર્ક્સ",
          "language": "ભાષા",
          "app settings": "એપ્લિકેશન સેટિંગ્સ",
          "logout": "લૉગ આઉટ",
          "change profile photo": "પ્રોફાઇલ ફોટો બદલો",
          "username": "વપરાશકર્તા નામ",
          "email": "ઈમેલ",
          "contact no": "સંપર્ક નં.",
          "save changes": "ફેરફારો સંગ્રહ",
          "current password": "અત્યારનો પાસવર્ડ",
          "type current password here": "વર્તમાન પાસવર્ડ અહીં ટાઈપ કરો",
          "new password": "નવો પાસવર્ડ",
          "type new password here": "અહીં નવો પાસવર્ડ ટાઈપ કરો",
          "confirm new password": "નવાપાસવર્ડની પુષ્ટી કરો",
          "type confirm new password here": "અહીં Confirm New Password લખો",
          "update password": "પાસવર્ડ અપડેટ કરો",
          "details": "વિગતો",
          "call": "કૉલ",
          "chat": "ચેટ",
          "month": "માસ",
          "govt. charges": "સરકાર. શુલ્ક",
          "description": "વર્ણન",
          "published on": "પર પ્રકાશિત",
          "sales enquiries": "વેચાણ પૂછપરછ",
          "app settings screen": "એપ્લિકેશન સેટિંગ્સ સ્ક્રીન",
          "display": "પ્રદર્શન",
          "dark mode": "ડાર્ક મોડ",
          "display mode": "પ્રદર્શન મોડ",
          "choose how your flutter ui kit experience looks for this device...": "આ ઉપકરણ માટે તમારો ફ્લટર UI કિટનો અનુભવ કેવો દેખાય છે તે પસંદ કરો...",
          "device settings": "ઉપકરણ સેટિંગ્સ",
          "light mode": "લાઇટ મોડ",
          "if you choose device settings, this app will use the mode that's already selected in this device's settings.": "જો તમે ઉપકરણ સેટિંગ્સ પસંદ કરો છો, તો આ એપ્લિકેશન તે મોડનો ઉપયોગ કરશે જે આ ઉપકરણની સેટિંગ્સમાં પહેલેથી પસંદ કરેલ છે.",
          "what are looking for?": "શું શોધી રહ્યા છો?",
          "current location": "અત્યારની જ્ગ્યા",
          "house": "ઘર",
          "flats / apartments": "ફ્લેટ / એપાર્ટમેન્ટ",
          "residential": "રહેણાંક",
          "commercial": "વ્યાપારી",
          "2000+ results": "2000+ પરિણામો",
          "5000+ results": "5000+ પરિણામો",
          "1000+ results": "1000+ પરિણામો",
          "recommend for you": "તમારા માટે ભલામણ કરો",
          "home": "ઘર",
          "location": "સ્થાન",
          "search location": "સ્થાન શોધો",
          "chats": "ચેટ્સ",
          "search by name": "નામ દ્વારા શોધો",
          "search by street/area/city": "શેરી/વિસ્તાર/શહેર દ્વારા શોધો",
          "use my current location": "મારા વર્તમાન સ્થાનનો ઉપયોગ કરો",
          "recent searches": "તાજેતરની શોધ",
          "view more": "વધુ જોવો",
          "type message here": "અહીં સંદેશ લખો",
        },
        'en': {
          "choose language": "Choose Language",
          "profile": "Profile",
          "edit profile": "Edit Profile",
          "change password": "Change Password",
          "bookmarks": "Bookmarks",
          "language": "Language",
          "app settings": "App Settings",
          "logout": "Logout",
          "change profile photo": "Change Profile Photo",
          "username": "Username",
          "email": "Email",
          "contact no": "Contact no.",
          "save changes": "Save Changes",
          "current password": "Current Password",
          "type current password here": "Type Current Password Here",
          "new password": "New Password",
          "type new password here": "Type New Password Here",
          "confirm new password": "Confirm New Password",
          "type confirm new password here": "Type Confirm New Password Here",
          "update password": "Update Password",
          "details": "Details",
          "call": "call",
          "chat": "Chat",
          "month": "month",
          "govt. charges": "Govt. Charges",
          "description": "Description",
          "published on": "Published On",
          "sales enquiries": "Sales Enquiries",
          "app settings screen": "App Settings Screen",
          "display": "Display",
          "dark mode": "Dark Mode",
          "display mode": "Display Mode",
          "choose how your flutter ui kit experience looks for this device...": "Choose how your Flutter UI Kit experience looks for this device...",
          "device settings": "Device Settings",
          "light mode": "Light Mode",
          "if you choose device settings, this app will use the mode that's already selected in this device's settings.": "If you choose Device settings, this app will use the mode that's already selected in this device's settings.",
          "what are looking for?": "What are looking for?",
          "current location": "Current location",
          "house": "House",
          "flats / apartments": "Flats / Apartments",
          "residential": "Residential",
          "commercial": "Commercial",
          "2000+ results": "2000+ results",
          "5000+ results": "5000+ results",
          "1000+ results": "1000+ results",
          "recommend for you": "Recommend For You",
          "home": "Home",
          "location": "Location",
          "search location": "Search Location",
          "chats": "Chats",
          "search by name": "Search by name",
          "search by street/area/city": "Search by street/area/city",
          "use my current location": "Use my current location",
          "recent searches": "RECENT SEARCHES",
          "view more": "View more",
          "type message here": "Type message here",
        },
        'he': {
          "choose language": "בחר שפה",
          "profile": "פּרוֹפִיל",
          "edit profile": "ערוך פרופיל",
          "change password": "שנה סיסמא",
          "bookmarks": "סימניות",
          "language": "שפה",
          "app settings": "הגדרות אפליקציה",
          "logout": "להתנתק",
          "change profile photo": "שנה תמונת פרופיל",
          "username": "שם משתמש",
          "email": "אימייל",
          "contact no": "מס' איש קשר.",
          "save changes": "שמור שינויים",
          "current password": "סיסמה נוכחית",
          "type current password here": "הקלד את הסיסמה הנוכחית כאן",
          "new password": "סיסמה חדשה",
          "type new password here": "הקלד סיסמה חדשה כאן",
          "confirm new password": "תאשר סיסמא חדשה",
          "type confirm new password here": "הקלד אשר סיסמה חדשה כאן",
          "update password": "עדכן סיסמה",
          "details": "פרטים",
          "call": "שִׂיחָה",
          "chat": "לְשׂוֹחֵחַ",
          "month": "חוֹדֶשׁ",
          "govt. charges": "Govt. חיובים",
          "description": "תיאור",
          "published on": "פורסם ב",
          "sales enquiries": "פניות מכירות",
          "app settings screen": "מסך הגדרות אפליקציה",
          "display": "לְהַצִיג",
          "dark mode": "מצב כהה",
          "display mode": "מצב תצוגה",
          "choose how your flutter ui kit experience looks for this device...": "בחר כיצד נראית חוויית ערכת ה-fladder ui שלך עבור המכשיר הזה...",
          "device settings": "הגדרות מכשיר",
          "light mode": "מצב אור",
          "if you choose device settings, this app will use the mode that's already selected in this device's settings.": "אם תבחר בהגדרות מכשיר, אפליקציה זו תשתמש במצב שכבר נבחר בהגדרות של מכשיר זה.",
          "what are looking for?": "מה מחפשים",
          "current location": "מיקום נוכחי",
          "house": "בַּיִת",
          "flats / apartments": "דירות / דירות",
          "residential": "מגורים",
          "commercial": "מִסְחָרִי",
          "2000+ results": "2000+ תוצאות",
          "5000+ results": "5000+ תוצאות",
          "1000+ results": "1000+ תוצאות",
          "recommend for you": "ממליץ בשבילך",
          "home": "בית",
          "location": "מקום",
          "search location": "חיפוש מיקום",
          "chats": "צ'אטים",
          "search by name": "חפש לפי שם",
          "search by street/area/city": "חפש לפי רחוב/אזור/עיר",
          "use my current location": "השתמש במיקום הנוכחי שלי",
          "recent searches": "חיפושים אחרונים",
          "view more": "ראה עוד",
          "type message here": "הקלד הודעה כאן",
        },
        'ar': {
          "choose language": "اختر اللغة",
          "profile": "حساب تعريفي",
          "edit profile": "تعديل الملف الشخصي",
          "change password": "تغيير كلمة المرور",
          "bookmarks": "إشارات مرجعية",
          "language": "لغة",
          "app settings": "إعدادات التطبيقات",
          "logout": "تسجيل خروج",
          "change profile photo": "تغيير صورة الملف الشخصي",
          "username": "اسم المستخدم",
          "email": "بريد إلكتروني",
          "contact no": "رقم الاتصال.",
          "save changes": "حفظ التغييرات",
          "current password": "كلمة السر الحالية",
          "type current password here": "اكتب كلمة المرور الحالية هنا",
          "new password": "كلمة المرور الجديدة",
          "type new password here": "اكتب كلمة المرور الجديدة هنا",
          "confirm new password": "تأكيد كلمة المرور الجديدة",
          "type confirm new password here": "اكتب تأكيد كلمة المرور الجديدة هنا",
          "update password": "تطوير كلمة السر",
          "details": "تفاصيل",
          "call": "يتصل",
          "chat": "محادثة",
          "month": "شهر",
          "govt. charges": "الحكومة. رسوم",
          "description": "وصف",
          "published on": "تم النشر بتاريخ",
          "sales enquiries": "استفسارات المبيعات",
          "app settings screen": "شاشة إعدادات التطبيق",
          "display": "عرض",
          "dark mode": "الوضع المظلم",
          "display mode": "وضع العرض",
          "choose how your flutter ui kit experience looks for this device...": "اختر كيف تبدو تجربة Flutter UI Kit لهذا الجهاز...",
          "device settings": "إعدادات الجهاز",
          "light mode": "وضع الضوء",
          "if you choose device settings, this app will use the mode that's already selected in this device's settings.": "إذا اخترت إعدادات الجهاز، فسيستخدم هذا التطبيق الوضع الذي تم تحديده بالفعل في إعدادات هذا الجهاز.",
          "what are looking for?": "عن ماذا تبحث؟",
          "current location": "الموقع الحالي",
          "house": "منزل",
          "flats / apartments": "شقق / شقق",
          "residential": "سكني",
          "commercial": "تجاري",
          "2000+ results": "أكثر من 2000 نتيجة",
          "5000+ results": "أكثر من 5000 نتيجة",
          "1000+ results": "أكثر من 1000 نتيجة",
          "recommend for you": "يوصي لك",
          "home": "بيت",
          "location": "موقع",
          "search location": "موقع البحث",
          "chats": "الدردشات",
          "search by name": "البحث عن طريق الإسم",
          "search by street/area/city": "البحث عن طريق الشارع / المنطقة / المدينة",
          "use my current location": "استخدام موقعي الحالي",
          "recent searches": "عمليات البحث الأخيرة",
          "view more": "عرض المزيد",
          "type message here": "اكتب الرسالة هنا",
        }
      };
}
